apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-deployment
  labels:
    app: camunda
spec:
  selector:
    matchLabels:
      app: camunda
  template:
    metadata:
      labels:
        app: camunda
    spec:
      containers:
      - name: camunda
        image: camunda/camunda-bpm-platform:run
        ports:
        - containerPort: 8080
