apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: camunda-ingress
spec:
  rules:
  - host: camunda.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: camunda-service
            port:
              name: http
