kind: Service
apiVersion: v1
metadata:
  name: camunda-service
  labels:
    app: camunda
spec:
  type: NodePort
  selector:
    app: camunda
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
